### ISSUE TITLE
FC 0.17 issue on creating a simple GDT

### ISSUE THREAD

**Issue by easyw** [juanvanyo/FreeCAD-GDT#3]
Hi, I'm testing GDT in FC 0.17 
OS: Windows 10 64-bit Version: 0.17.11967 (Git)
I followed the README instruction and in FC 0.17 Adding a simple Datum Feature I get the following error:

> Traceback (most recent call last):
  File "C:\Users\userC\AppData\Roaming\FreeCAD\Mod\GDT\GDT.py", line 1171, in updateData
    fp.circumferenceBool = True if (True in [l.Closed for l in fp.faces[0][0].Shape.getElement(fp.faces[0][1]).Edges] and len(fp.faces[0][0].Shape.getElement(fp.faces[0][1]).Vertexes) == 2) else False
<type 'exceptions.TypeError'>: must be string, not tuple
Traceback (most recent call last):
  File "C:\Users\userC\AppData\Roaming\FreeCAD\Mod\GDT\GDT.py", line 1451, in createObject
    obj = makeDatumFeature(self.textName, self.ContainerOfData)
  File "C:\Users\userC\AppData\Roaming\FreeCAD\Mod\GDT\GDT.py", line 834, in makeDatumFeature
    makeAnnotation(ContainerOfData.faces, ContainerOfData.annotationPlane, DF=obj, GT=[])
  File "C:\Users\userC\AppData\Roaming\FreeCAD\Mod\GDT\GDT.py", line 1243, in makeAnnotation
    obj.p1 = (obj.faces[0][0].Shape.getElement(obj.faces[0][1]).CenterOfMass).projectToPlane(obj.AP.PointWithOffset, obj.AP.Direction)
TypeError: must be string, not tuple

This happens also if I create a GDT in FC0.16, save the file and then open it in FC0.17

> Object can only be in a single Group
Traceback (most recent call last):
  File "C:\Users\userC\AppData\Roaming\FreeCAD\Mod\GDT\GDT.py", line 1171, in updateData
    fp.circumferenceBool = True if (True in [l.Closed for l in fp.faces[0][0].Shape.getElement(fp.faces[0][1]).Edges] and len(fp.faces[0][0].Shape.getElement(fp.faces[0][1]).Vertexes) == 2) else False
<type 'exceptions.TypeError'>: must be string, not tuple

Maurice

**Comment by Nemesis81** [comment]
Same with latest 0.17 version (released)

**Comment by luzpaz** [comment]
@juanvanyo ping

**Comment by aversario** [comment]
@juanvanyo
